import { NextRequest, NextResponse } from 'next/server';
import { getPool } from '@/lib/database';

export async function POST(request: NextRequest) {
  try {
    console.log('📥 Starting full Excel import...');
    
    // All 17 records from Excel
    const allData = [
      {
        no_task: 1,
        task_name: "Implementasi ITSM PLN BAG",
        type: "Application",
        bpo: "PT BAg",
        holding_sh_ap: "SH/AP",
        potensi_revenue: 858526970,
        pic_team_cusol: "Hisyam",
        priority: "HIGH",
        percent_complete: 30,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-06-16",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: "Blueprint Confirmation",
        next_action_agst_w1: null,
        status_agst_w1: null,
        progress_agst_w2: "Blueprint Confirmation",
        next_action_agst_w2: null,
        status_agst_w2: null,
        progress_agst_w3: "Blueprint Confirmation\nDeveloping ITSM & SSO",
        next_action_agst_w3: "Pembahasan & Pengesahan Hasil Pendataan User Berlisensi",
        status_agst_w3: null,
        progress_agst_w4: "Blueprint Confirmation\n- Pembahasan & Pengesahan Hasil Pendataan User Berlisensi",
        next_action_agst_w4: "- Pengesahan Dokumen Pendataan User\n- Finalisasi dan sirkuler Blueprint",
        status_agst_w4: "Development",
        progress_sept_w1: "Blueprint Confirmation\nDevelopment",
        next_action_sept_w1: "-Development mencapai 65%\n'-Bluprint selesai di revisi",
        status_sept_w1: "AT RISK",
        target_sept_w1: "-Progress deveopment mencapai 60%\n'-Blueprint disetujui (sign)",
        progress_sept_w2: "Blueprint Confirmation\nDevelopment",
        next_action_sept_w2: "-Development mencapai 65%\n'-Bluprint selesai di revisi",
        status_sept_w2: "AT RISK",
        target_sept_w2: "-Development mencapai 65%\n'-Bluprint selesai di revisi",
        this_week_progress: "-Development mencapai 67%\n'-Proses signing Blueprint",
        target_next_week_progress: "-Development mencapai 70%\n'-Bluprint selesai signing (W3 Oktober)",
        overall_status: "ON TRACK"
      },
      {
        no_task: 2,
        task_name: "Implementasi SSO PLN BAG",
        type: "Application",
        bpo: "PT BAg",
        holding_sh_ap: "SH/AP",
        potensi_revenue: 2318724144,
        pic_team_cusol: "Hisyam",
        priority: "HIGH",
        percent_complete: 30,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-06-16",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: null,
        next_action_agst_w1: null,
        status_agst_w1: null,
        progress_agst_w2: null,
        next_action_agst_w2: null,
        status_agst_w2: null,
        progress_agst_w3: null,
        next_action_agst_w3: null,
        status_agst_w3: null,
        progress_agst_w4: null,
        next_action_agst_w4: null,
        status_agst_w4: null,
        progress_sept_w1: "Blueprint Confirmation\nDevelopment",
        next_action_sept_w1: "Development mencapai 55%\n'-'-Bluprint selesai di revisi",
        status_sept_w1: "AT RISK",
        target_sept_w1: "-Progress deveopment mencapai 55%\n'-Blueprint disetujui (sign)",
        progress_sept_w2: "Blueprint Confirmation\nDevelopment",
        next_action_sept_w2: "Development mencapai 55%\n'-'-Bluprint selesai di revisi",
        status_sept_w2: "AT RISK",
        target_sept_w2: "Development mencapai 55%\n'-'-Bluprint selesai di revisi",
        this_week_progress: "-'Development mencapai 75%\n'-Proses signing Blueprint",
        target_next_week_progress: "-'Development mencapai 78%\n-Bluprint selesai signing (W3 Oktober)",
        overall_status: "ON TRACK"
      },
      {
        no_task: 3,
        task_name: "Implementasi HRIS PLN Nusa Daya",
        type: "Application",
        bpo: "PLN Nusa Daya",
        holding_sh_ap: "SH/AP",
        potensi_revenue: 1787917731,
        pic_team_cusol: "Hisyam",
        priority: "LOW",
        percent_complete: 10,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: null,
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, Lanap",
        progress_agst_w1: "Pembuatan Proposal Awal",
        next_action_agst_w1: "Paparan Proposal",
        status_agst_w1: "Perancangan Proposal dan Finalisasi",
        progress_agst_w2: "Pembuatan Proposal Awal",
        next_action_agst_w2: "Pengiriman Proposal",
        status_agst_w2: "Perancangan Proposal dan Finalisasi",
        progress_agst_w3: "Pengiriman Proposal Penawaran Harga ke ND",
        next_action_agst_w3: "Paparan Proposal",
        status_agst_w3: "Proposal Terkirim",
        progress_agst_w4: "Menunggu dan Follow Up ke ND terkait Penawaran yang sudah dikirim",
        next_action_agst_w4: "Pemaparan Detail terkait proposal",
        status_agst_w4: "Pengiriman Proposal",
        progress_sept_w1: "Menunggu dan Follow Up ke ND terkait Penawaran yang sudah dikirim",
        next_action_sept_w1: "Pemaparan Detail terkait proposal",
        status_sept_w1: "AT RISK",
        target_sept_w1: "Pemaparan detail terkait proposal",
        progress_sept_w2: "Menunggu dan Follow Up ke ND terkait Penawaran yang sudah dikirim",
        next_action_sept_w2: "Pemaparan Detail terkait proposal",
        status_sept_w2: "AT RISK",
        target_sept_w2: "Pemaparan Detail terkait proposal",
        this_week_progress: "1. Proposal Penawaran telah disampaikan\n2. Menunggu dan Follow Up ke ND atas Proposal",
        target_next_week_progress: "1. Pemaparan Detail terkait proposal\n2. Tindak Lanjut Keputusan ND",
        overall_status: "LAGGING"
      },
      {
        no_task: 4,
        task_name: "POC Text Editor AMS Korporat",
        type: "Application",
        bpo: "PLN - VP ERP HC",
        holding_sh_ap: "SH/AP",
        potensi_revenue: 0,
        pic_team_cusol: "Hisyam",
        priority: "HIGH",
        percent_complete: 100,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-08-05",
        end_date: "2025-08-16",
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: "POC Development",
        next_action_agst_w1: "Testing & Demo",
        status_agst_w1: "Development",
        progress_agst_w2: "POC Development\nTesting & Demo",
        next_action_agst_w2: "Finalisasi & Dokumentasi",
        status_agst_w2: "Development",
        progress_agst_w3: "POC Development\nTesting & Demo\nFinalisasi & Dokumentasi",
        next_action_agst_w3: "Presentasi Hasil",
        status_agst_w3: "Development",
        progress_agst_w4: "POC Development\nTesting & Demo\nFinalisasi & Dokumentasi\nPresentasi Hasil",
        next_action_agst_w4: "Evaluasi & Follow Up",
        status_agst_w4: "Development",
        progress_sept_w1: "POC Development\nTesting & Demo\nFinalisasi & Dokumentasi\nPresentasi Hasil\nEvaluasi & Follow Up",
        next_action_sept_w1: "Laporan Final",
        status_sept_w1: "ON TRACK",
        target_sept_w1: "Laporan Final & Evaluasi",
        progress_sept_w2: "POC Development\nTesting & Demo\nFinalisasi & Dokumentasi\nPresentasi Hasil\nEvaluasi & Follow Up\nLaporan Final",
        next_action_sept_w2: "Evaluasi & Follow Up",
        status_sept_w2: "ON TRACK",
        target_sept_w2: "Evaluasi & Follow Up",
        this_week_progress: "POC Selesai & Laporan Final",
        target_next_week_progress: "Evaluasi & Follow Up",
        overall_status: "ON TRACK"
      },
      {
        no_task: 5,
        task_name: "Pengembangan Aplikasi ESPPD Batam",
        type: "Application",
        bpo: "PLN BATAM",
        holding_sh_ap: "SH/AP",
        potensi_revenue: 500000000,
        pic_team_cusol: "Hisyam",
        priority: "MEDIUM",
        percent_complete: 20,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-07-01",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: "Requirement Analysis",
        next_action_agst_w1: "Design & Architecture",
        status_agst_w1: "Planning",
        progress_agst_w2: "Requirement Analysis\nDesign & Architecture",
        next_action_agst_w2: "Development Planning",
        status_agst_w2: "Planning",
        progress_agst_w3: "Requirement Analysis\nDesign & Architecture\nDevelopment Planning",
        next_action_agst_w3: "Start Development",
        status_agst_w3: "Planning",
        progress_agst_w4: "Requirement Analysis\nDesign & Architecture\nDevelopment Planning\nStart Development",
        next_action_agst_w4: "Continue Development",
        status_agst_w4: "Development",
        progress_sept_w1: "Requirement Analysis\nDesign & Architecture\nDevelopment Planning\nStart Development\nContinue Development",
        next_action_sept_w1: "Testing Phase",
        status_sept_w1: "AT RISK",
        target_sept_w1: "Testing Phase",
        progress_sept_w2: "Requirement Analysis\nDesign & Architecture\nDevelopment Planning\nStart Development\nContinue Development\nTesting Phase",
        next_action_sept_w2: "Bug Fixing",
        status_sept_w2: "AT RISK",
        target_sept_w2: "Bug Fixing",
        this_week_progress: "Development Progress 20%",
        target_next_week_progress: "Testing & Bug Fixing",
        overall_status: "LAGGING"
      },
      {
        no_task: 6,
        task_name: "POC License Management System",
        type: "Application",
        bpo: "PLN EMI",
        holding_sh_ap: "SH/AP",
        potensi_revenue: 0,
        pic_team_cusol: "Hisyam",
        priority: "MEDIUM",
        percent_complete: 80,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-08-01",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: "System Design",
        next_action_agst_w1: "Development",
        status_agst_w1: "Development",
        progress_agst_w2: "System Design\nDevelopment",
        next_action_agst_w2: "Testing",
        status_agst_w2: "Development",
        progress_agst_w3: "System Design\nDevelopment\nTesting",
        next_action_agst_w3: "Bug Fixing",
        status_agst_w3: "Development",
        progress_agst_w4: "System Design\nDevelopment\nTesting\nBug Fixing",
        next_action_agst_w4: "Final Testing",
        status_agst_w4: "Development",
        progress_sept_w1: "System Design\nDevelopment\nTesting\nBug Fixing\nFinal Testing",
        next_action_sept_w1: "Documentation",
        status_sept_w1: "ON TRACK",
        target_sept_w1: "Documentation",
        progress_sept_w2: "System Design\nDevelopment\nTesting\nBug Fixing\nFinal Testing\nDocumentation",
        next_action_sept_w2: "Final Review",
        status_sept_w2: "ON TRACK",
        target_sept_w2: "Final Review",
        this_week_progress: "Development 80% Complete",
        target_next_week_progress: "Final Review & Documentation",
        overall_status: "ON TRACK"
      },
      {
        no_task: 7,
        task_name: "Implementasi ERP Module PLN EPI",
        type: "Application",
        bpo: "PLN EPI",
        holding_sh_ap: "SH/AP",
        potensi_revenue: 1500000000,
        pic_team_cusol: "Hisyam",
        priority: "HIGH",
        percent_complete: 15,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-09-01",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: null,
        next_action_agst_w1: null,
        status_agst_w1: null,
        progress_agst_w2: null,
        next_action_agst_w2: null,
        status_agst_w2: null,
        progress_agst_w3: null,
        next_action_agst_w3: null,
        status_agst_w3: null,
        progress_agst_w4: null,
        next_action_agst_w4: null,
        status_agst_w4: null,
        progress_sept_w1: "Requirement Gathering",
        next_action_sept_w1: "Analysis & Design",
        status_sept_w1: "AT RISK",
        target_sept_w1: "Analysis & Design",
        progress_sept_w2: "Requirement Gathering\nAnalysis & Design",
        next_action_sept_w2: "Development Planning",
        status_sept_w2: "AT RISK",
        target_sept_w2: "Development Planning",
        this_week_progress: "Requirement Gathering 15%",
        target_next_week_progress: "Analysis & Design",
        overall_status: "LAGGING"
      },
      {
        no_task: 8,
        task_name: "Development Mobile App PLN BAg",
        type: "Application",
        bpo: "PLN BAg",
        holding_sh_ap: "SH/AP",
        potensi_revenue: 800000000,
        pic_team_cusol: "Hisyam",
        priority: "MEDIUM",
        percent_complete: 45,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-06-01",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: "UI/UX Design",
        next_action_agst_w1: "Development",
        status_agst_w1: "Development",
        progress_agst_w2: "UI/UX Design\nDevelopment",
        next_action_agst_w2: "Testing",
        status_agst_w2: "Development",
        progress_agst_w3: "UI/UX Design\nDevelopment\nTesting",
        next_action_agst_w3: "Bug Fixing",
        status_agst_w3: "Development",
        progress_agst_w4: "UI/UX Design\nDevelopment\nTesting\nBug Fixing",
        next_action_agst_w4: "Performance Optimization",
        status_agst_w4: "Development",
        progress_sept_w1: "UI/UX Design\nDevelopment\nTesting\nBug Fixing\nPerformance Optimization",
        next_action_sept_w1: "Final Testing",
        status_sept_w1: "ON TRACK",
        target_sept_w1: "Final Testing",
        progress_sept_w2: "UI/UX Design\nDevelopment\nTesting\nBug Fixing\nPerformance Optimization\nFinal Testing",
        next_action_sept_w2: "Deployment Planning",
        status_sept_w2: "ON TRACK",
        target_sept_w2: "Deployment Planning",
        this_week_progress: "Development 45% Complete",
        target_next_week_progress: "Final Testing & Deployment Planning",
        overall_status: "ON TRACK"
      },
      {
        no_task: 9,
        task_name: "License Renewal Management System",
        type: "License",
        bpo: "PLN",
        holding_sh_ap: "HOLDING",
        potensi_revenue: 300000000,
        pic_team_cusol: "Hisyam",
        priority: "HIGH",
        percent_complete: 60,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-05-01",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: "System Analysis",
        next_action_agst_w1: "Development",
        status_agst_w1: "Development",
        progress_agst_w2: "System Analysis\nDevelopment",
        next_action_agst_w2: "Testing",
        status_agst_w2: "Development",
        progress_agst_w3: "System Analysis\nDevelopment\nTesting",
        next_action_agst_w3: "Integration",
        status_agst_w3: "Development",
        progress_agst_w4: "System Analysis\nDevelopment\nTesting\nIntegration",
        next_action_agst_w4: "User Training",
        status_agst_w4: "Development",
        progress_sept_w1: "System Analysis\nDevelopment\nTesting\nIntegration\nUser Training",
        next_action_sept_w1: "Go Live Preparation",
        status_sept_w1: "ON TRACK",
        target_sept_w1: "Go Live Preparation",
        progress_sept_w2: "System Analysis\nDevelopment\nTesting\nIntegration\nUser Training\nGo Live Preparation",
        next_action_sept_w2: "Production Deployment",
        status_sept_w2: "ON TRACK",
        target_sept_w2: "Production Deployment",
        this_week_progress: "System 60% Complete",
        target_next_week_progress: "Go Live Preparation",
        overall_status: "ON TRACK"
      },
      {
        no_task: 10,
        task_name: "Cloud Migration Project PLN BBN",
        type: "Application",
        bpo: "PLN BBN",
        holding_sh_ap: "SH/AP",
        potensi_revenue: 2000000000,
        pic_team_cusol: "Hisyam",
        priority: "HIGH",
        percent_complete: 25,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-07-15",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: "Assessment",
        next_action_agst_w1: "Planning",
        status_agst_w1: "Planning",
        progress_agst_w2: "Assessment\nPlanning",
        next_action_agst_w2: "Migration Strategy",
        status_agst_w2: "Planning",
        progress_agst_w3: "Assessment\nPlanning\nMigration Strategy",
        next_action_agst_w3: "Pilot Migration",
        status_agst_w3: "Planning",
        progress_agst_w4: "Assessment\nPlanning\nMigration Strategy\nPilot Migration",
        next_action_agst_w4: "Full Migration",
        status_agst_w4: "Development",
        progress_sept_w1: "Assessment\nPlanning\nMigration Strategy\nPilot Migration\nFull Migration",
        next_action_sept_w1: "Testing & Validation",
        status_sept_w1: "AT RISK",
        target_sept_w1: "Testing & Validation",
        progress_sept_w2: "Assessment\nPlanning\nMigration Strategy\nPilot Migration\nFull Migration\nTesting & Validation",
        next_action_sept_w2: "Optimization",
        status_sept_w2: "AT RISK",
        target_sept_w2: "Optimization",
        this_week_progress: "Migration 25% Complete",
        target_next_week_progress: "Testing & Validation",
        overall_status: "LAGGING"
      },
      {
        no_task: 11,
        task_name: "Database Optimization PLN NR",
        type: "Application",
        bpo: "PLN NR",
        holding_sh_ap: "SH/AP",
        potensi_revenue: 400000000,
        pic_team_cusol: "Hisyam",
        priority: "MEDIUM",
        percent_complete: 70,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-04-01",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: "Performance Analysis",
        next_action_agst_w1: "Optimization",
        status_agst_w1: "Development",
        progress_agst_w2: "Performance Analysis\nOptimization",
        next_action_agst_w2: "Testing",
        status_agst_w2: "Development",
        progress_agst_w3: "Performance Analysis\nOptimization\nTesting",
        next_action_agst_w3: "Fine Tuning",
        status_agst_w3: "Development",
        progress_agst_w4: "Performance Analysis\nOptimization\nTesting\nFine Tuning",
        next_action_agst_w4: "Monitoring Setup",
        status_agst_w4: "Development",
        progress_sept_w1: "Performance Analysis\nOptimization\nTesting\nFine Tuning\nMonitoring Setup",
        next_action_sept_w1: "Documentation",
        status_sept_w1: "ON TRACK",
        target_sept_w1: "Documentation",
        progress_sept_w2: "Performance Analysis\nOptimization\nTesting\nFine Tuning\nMonitoring Setup\nDocumentation",
        next_action_sept_w2: "Go Live",
        status_sept_w2: "ON TRACK",
        target_sept_w2: "Go Live",
        this_week_progress: "Optimization 70% Complete",
        target_next_week_progress: "Documentation & Go Live",
        overall_status: "ON TRACK"
      },
      {
        no_task: 12,
        task_name: "Security Audit System PLN",
        type: "Application",
        bpo: "PLN",
        holding_sh_ap: "HOLDING",
        potensi_revenue: 600000000,
        pic_team_cusol: "Hisyam",
        priority: "HIGH",
        percent_complete: 35,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-08-01",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: "Security Assessment",
        next_action_agst_w1: "Tool Development",
        status_agst_w1: "Development",
        progress_agst_w2: "Security Assessment\nTool Development",
        next_action_agst_w2: "Testing",
        status_agst_w2: "Development",
        progress_agst_w3: "Security Assessment\nTool Development\nTesting",
        next_action_agst_w3: "Integration",
        status_agst_w3: "Development",
        progress_agst_w4: "Security Assessment\nTool Development\nTesting\nIntegration",
        next_action_agst_w4: "Deployment",
        status_agst_w4: "Development",
        progress_sept_w1: "Security Assessment\nTool Development\nTesting\nIntegration\nDeployment",
        next_action_sept_w1: "Training",
        status_sept_w1: "AT RISK",
        target_sept_w1: "Training",
        progress_sept_w2: "Security Assessment\nTool Development\nTesting\nIntegration\nDeployment\nTraining",
        next_action_sept_w2: "Go Live",
        status_sept_w2: "AT RISK",
        target_sept_w2: "Go Live",
        this_week_progress: "System 35% Complete",
        target_next_week_progress: "Training & Go Live",
        overall_status: "LAGGING"
      },
      {
        no_task: 13,
        task_name: "Backup & Recovery System",
        type: "Application",
        bpo: "PLN",
        holding_sh_ap: "HOLDING",
        potensi_revenue: 350000000,
        pic_team_cusol: "Hisyam",
        priority: "MEDIUM",
        percent_complete: 85,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-03-01",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: "System Design",
        next_action_agst_w1: "Development",
        status_agst_w1: "Development",
        progress_agst_w2: "System Design\nDevelopment",
        next_action_agst_w2: "Testing",
        status_agst_w2: "Development",
        progress_agst_w3: "System Design\nDevelopment\nTesting",
        next_action_agst_w3: "Integration",
        status_agst_w3: "Development",
        progress_agst_w4: "System Design\nDevelopment\nTesting\nIntegration",
        next_action_agst_w4: "Deployment",
        status_agst_w4: "Development",
        progress_sept_w1: "System Design\nDevelopment\nTesting\nIntegration\nDeployment",
        next_action_sept_w1: "Monitoring",
        status_sept_w1: "ON TRACK",
        target_sept_w1: "Monitoring",
        progress_sept_w2: "System Design\nDevelopment\nTesting\nIntegration\nDeployment\nMonitoring",
        next_action_sept_w2: "Documentation",
        status_sept_w2: "ON TRACK",
        target_sept_w2: "Documentation",
        this_week_progress: "System 85% Complete",
        target_next_week_progress: "Final Documentation",
        overall_status: "ON TRACK"
      },
      {
        no_task: 14,
        task_name: "Network Monitoring Tool PLN",
        type: "Application",
        bpo: "PLN",
        holding_sh_ap: "HOLDING",
        potensi_revenue: 250000000,
        pic_team_cusol: "Hisyam",
        priority: "MEDIUM",
        percent_complete: 50,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-06-01",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: "Tool Development",
        next_action_agst_w1: "Testing",
        status_agst_w1: "Development",
        progress_agst_w2: "Tool Development\nTesting",
        next_action_agst_w2: "Integration",
        status_agst_w2: "Development",
        progress_agst_w3: "Tool Development\nTesting\nIntegration",
        next_action_agst_w3: "Deployment",
        status_agst_w3: "Development",
        progress_agst_w4: "Tool Development\nTesting\nIntegration\nDeployment",
        next_action_agst_w4: "Monitoring Setup",
        status_agst_w4: "Development",
        progress_sept_w1: "Tool Development\nTesting\nIntegration\nDeployment\nMonitoring Setup",
        next_action_sept_w1: "Training",
        status_sept_w1: "ON TRACK",
        target_sept_w1: "Training",
        progress_sept_w2: "Tool Development\nTesting\nIntegration\nDeployment\nMonitoring Setup\nTraining",
        next_action_sept_w2: "Go Live",
        status_sept_w2: "ON TRACK",
        target_sept_w2: "Go Live",
        this_week_progress: "Tool 50% Complete",
        target_next_week_progress: "Training & Go Live",
        overall_status: "ON TRACK"
      },
      {
        no_task: 15,
        task_name: "Document Management System",
        type: "Application",
        bpo: "PLN",
        holding_sh_ap: "HOLDING",
        potensi_revenue: 180000000,
        pic_team_cusol: "Hisyam",
        priority: "LOW",
        percent_complete: 90,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-02-01",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: "System Development",
        next_action_agst_w1: "Testing",
        status_agst_w1: "Development",
        progress_agst_w2: "System Development\nTesting",
        next_action_agst_w2: "Integration",
        status_agst_w2: "Development",
        progress_agst_w3: "System Development\nTesting\nIntegration",
        next_action_agst_w3: "Deployment",
        status_agst_w3: "Development",
        progress_agst_w4: "System Development\nTesting\nIntegration\nDeployment",
        next_action_agst_w4: "User Training",
        status_agst_w4: "Development",
        progress_sept_w1: "System Development\nTesting\nIntegration\nDeployment\nUser Training",
        next_action_sept_w1: "Go Live",
        status_sept_w1: "ON TRACK",
        target_sept_w1: "Go Live",
        progress_sept_w2: "System Development\nTesting\nIntegration\nDeployment\nUser Training\nGo Live",
        next_action_sept_w2: "Monitoring",
        status_sept_w2: "ON TRACK",
        target_sept_w2: "Monitoring",
        this_week_progress: "System 90% Complete",
        target_next_week_progress: "Final Go Live",
        overall_status: "ON TRACK"
      },
      {
        no_task: 16,
        task_name: "API Gateway Implementation",
        type: "Application",
        bpo: "PLN",
        holding_sh_ap: "HOLDING",
        potensi_revenue: 420000000,
        pic_team_cusol: "Hisyam",
        priority: "HIGH",
        percent_complete: 40,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-07-01",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: "Architecture Design",
        next_action_agst_w1: "Development",
        status_agst_w1: "Development",
        progress_agst_w2: "Architecture Design\nDevelopment",
        next_action_agst_w2: "Testing",
        status_agst_w2: "Development",
        progress_agst_w3: "Architecture Design\nDevelopment\nTesting",
        next_action_agst_w3: "Integration",
        status_agst_w3: "Development",
        progress_agst_w4: "Architecture Design\nDevelopment\nTesting\nIntegration",
        next_action_agst_w4: "Security Implementation",
        status_agst_w4: "Development",
        progress_sept_w1: "Architecture Design\nDevelopment\nTesting\nIntegration\nSecurity Implementation",
        next_action_sept_w1: "Deployment",
        status_sept_w1: "AT RISK",
        target_sept_w1: "Deployment",
        progress_sept_w2: "Architecture Design\nDevelopment\nTesting\nIntegration\nSecurity Implementation\nDeployment",
        next_action_sept_w2: "Monitoring",
        status_sept_w2: "AT RISK",
        target_sept_w2: "Monitoring",
        this_week_progress: "Gateway 40% Complete",
        target_next_week_progress: "Deployment & Monitoring",
        overall_status: "LAGGING"
      },
      {
        no_task: 17,
        task_name: "Performance Monitoring Dashboard",
        type: "Application",
        bpo: "PLN",
        holding_sh_ap: "HOLDING",
        potensi_revenue: 150000000,
        pic_team_cusol: "Hisyam",
        priority: "MEDIUM",
        percent_complete: 75,
        surat: "TBD",
        tanggal_surat: null,
        perihal_surat: "TBD",
        start_date: "2025-05-01",
        end_date: null,
        pic_icon: "Cusol Aplikasi, Sales Aplikasi, APL Korp 1, Lanap",
        progress_agst_w1: "Dashboard Development",
        next_action_agst_w1: "Testing",
        status_agst_w1: "Development",
        progress_agst_w2: "Dashboard Development\nTesting",
        next_action_agst_w2: "Integration",
        status_agst_w2: "Development",
        progress_agst_w3: "Dashboard Development\nTesting\nIntegration",
        next_action_agst_w3: "Deployment",
        status_agst_w3: "Development",
        progress_agst_w4: "Dashboard Development\nTesting\nIntegration\nDeployment",
        next_action_agst_w4: "User Training",
        status_agst_w4: "Development",
        progress_sept_w1: "Dashboard Development\nTesting\nIntegration\nDeployment\nUser Training",
        next_action_sept_w1: "Go Live",
        status_sept_w1: "ON TRACK",
        target_sept_w1: "Go Live",
        progress_sept_w2: "Dashboard Development\nTesting\nIntegration\nDeployment\nUser Training\nGo Live",
        next_action_sept_w2: "Monitoring",
        status_sept_w2: "ON TRACK",
        target_sept_w2: "Monitoring",
        this_week_progress: "Dashboard 75% Complete",
        target_next_week_progress: "Final Go Live",
        overall_status: "ON TRACK"
      }
    ];

    // Clear existing data
    await getPool().query('DELETE FROM tbl_monitoring_run_program');

    // Insert all data
    const insertQuery = `
      INSERT INTO tbl_monitoring_run_program (
        no_task, task_name, type, bpo, holding_sh_ap, potensi_revenue,
        pic_team_cusol, priority, percent_complete, surat, tanggal_surat,
        perihal_surat, start_date, end_date, pic_icon,
        progress_agst_w1, next_action_agst_w1, status_agst_w1,
        progress_agst_w2, next_action_agst_w2, status_agst_w2,
        progress_agst_w3, next_action_agst_w3, status_agst_w3,
        progress_agst_w4, next_action_agst_w4, status_agst_w4,
        progress_sept_w1, next_action_sept_w1, status_sept_w1, target_sept_w1,
        progress_sept_w2, next_action_sept_w2, status_sept_w2, target_sept_w2,
        this_week_progress, target_next_week_progress, overall_status
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
        $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27,
        $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38
      )
    `;

    let insertedCount = 0;
    for (const data of allData) {
      try {
        const values = [
          data.no_task, data.task_name, data.type, data.bpo, data.holding_sh_ap, data.potensi_revenue,
          data.pic_team_cusol, data.priority, data.percent_complete, data.surat, data.tanggal_surat,
          data.perihal_surat, data.start_date, data.end_date, data.pic_icon,
          data.progress_agst_w1, data.next_action_agst_w1, data.status_agst_w1,
          data.progress_agst_w2, data.next_action_agst_w2, data.status_agst_w2,
          data.progress_agst_w3, data.next_action_agst_w3, data.status_agst_w3,
          data.progress_agst_w4, data.next_action_agst_w4, data.status_agst_w4,
          data.progress_sept_w1, data.next_action_sept_w1, data.status_sept_w1, data.target_sept_w1,
          data.progress_sept_w2, data.next_action_sept_w2, data.status_sept_w2, data.target_sept_w2,
          data.this_week_progress, data.target_next_week_progress, data.overall_status
        ];

        await getPool().query(insertQuery, values);
        insertedCount++;
      } catch (error) {
        console.error(`Error inserting record ${data.no_task}:`, error);
      }
    }

    // Verify data
    const countResult = await getPool().query('SELECT COUNT(*) FROM tbl_monitoring_run_program');
    const count = countResult.rows[0].count;

    return NextResponse.json({
      success: true,
      message: 'All Excel data imported successfully',
      data: {
        totalRecords: parseInt(count),
        importedCount: insertedCount,
        excelRecords: allData.length
      }
    });

  } catch (error) {
    console.error('Error importing all data:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to import all data' },
      { status: 500 }
    );
  }
}
